# Use the official Node.js 14 image as a parent image
FROM node:18-alpine

# Set the working directory inside docker container
WORKDIR /app

# Copy the file from your host to your current location.
COPY package.json .

# Run the command inside your image filesystem.
RUN npm install

# Inform Docker that the container is listening on the specified port at runtime.
EXPOSE 3000

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

RUN export NODE_ENV=development

# RUN npm run build

# Run the specified command within the container.
# CMD ["nuxt", "start", "-H", "0.0.0.0"]

